### ISSUE TITLE
SayAnything Blog Link

### ISSUE THREAD

**Issue by jgrinsteinner** [openfcci/fcc-global-nav#16]
### Overview

The link to Say Anything Blog is pointing to https://sayanythingblog.com. Dustin has updated the server alias and placed a redirect, but it is a bit pokey to load. Could we update the Global Nav to point to https://www.sayanythingblog.com?
#### Checklist
- [ ] Update link in global nav
### Reference
- [#](Link)

**Comment by rveitch** [comment]
Reviewed and accepted [Branden's PR](https://github.com/openfcci/fcc-global-nav/pull/17) for this issue. Updated code is now live.
